# Use MySQL official image
FROM mysql:latest

# Set environment variables for MySQL (values will be set in Render's dashboard)
ENV MYSQL_DATABASE=sema_mama_db
ENV MYSQL_USER=Diana
ENV MYSQL_PASSWORD=Dee0000!
ENV MYSQL_ROOT_PASSWORD=Dee0000!

# Expose MySQL port
EXPOSE 3306
