version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: sema_mama_db
      MYSQL_USER: Diana
      MYSQL_PASSWORD: Dee0000!
      MYSQL_ROOT_PASSWORD: Dee0000!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
