# Generated by Django 5.1.7 on 2025-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('virtual', 'Virtual Consultation'), ('in_person', 'In-Person Visit')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes_for_provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='technical_requirements',
            field=models.TextField(blank=True, help_text='Any technical requirements or preferences for virtual consultation', null=True),
        ),
    ]
