# Generated by Django 5.1.7 on 2025-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
