# Generated by Django 5.1.7 on 2025-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
