# Generated by Django 5.1.7 on 2025-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpartumdepressionquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
