# Generated by Django 5.1.6 on 2025-02-21 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French')], default='en', max_length=10)),
                ('dark_mode', models.BooleanField(default=False)),
                ('notifications', models.CharField(choices=[('all', 'All Notifications'), ('email', 'Email Only'), ('sms', 'SMS Only'), ('none', 'No Notifications')], default='all', max_length=10)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=10)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('EAT', 'East Africa Time'), ('CET', 'Central European Time')], default='UTC', max_length=10)),
                ('content_preferences', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
