# Generated by Django 5.1.7 on 2025-03-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0002_postpartumdepressionquestion_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postpartumdepressionquestion',
            table='mama_postpartumdepressionquestion',
        ),
    ]
