# Generated by Django 5.1.7 on 2025-03-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0003_alter_postpartumdepressionquestion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('picture', 'Picture'), ('youtube', 'YouTube Link')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='info_files/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
