# Generated by Django 5.1.7 on 2025-03-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0004_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotional_state', models.CharField(choices=[('very_happy', 'Very Happy and Content'), ('mostly_good', 'Mostly Good'), ('up_and_down', 'Up and Down'), ('somewhat_low', 'Somewhat Low'), ('very_low', 'Very Low or Depressed')], max_length=50)),
                ('anxiety_level', models.CharField(max_length=50)),
                ('sleep_quality', models.CharField(max_length=50)),
                ('social_support', models.CharField(max_length=50)),
                ('physical_symptoms', models.CharField(max_length=50)),
                ('baby_bonding', models.CharField(max_length=50)),
                ('self_care', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
