# Generated by Django 5.1.7 on 2025-03-28 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0008_chatmessage_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'recipient'], name='mama_chatme_sender__bc03ee_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='mama_chatme_timesta_9bdd54_idx'),
        ),
    ]
