# Generated by Django 5.1.7 on 2025-03-30 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Forums'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AddIndex(
            model_name='forum',
            index=models.Index(fields=['created_at'], name='community_f_created_4bdabe_idx'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='community_comment',
        ),
        migrations.AlterModelTable(
            name='forum',
            table='community_forum',
        ),
        migrations.AlterModelTable(
            name='post',
            table='community_post',
        ),
    ]
