# Generated by Django 5.1.7 on 2025-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_normalize_forum_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('Pregnancy', 'Pregnancy'), ('Postpartum', 'Postpartum'), ('Parenting', 'Parenting'), ('Mental Health', 'Mental Health'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
