# Generated by Django 5.1.6 on 2025-03-03 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_forum_name_alter_forum_visibility_post_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='forums', to=settings.AUTH_USER_MODEL),
        ),
    ]
