# Generated by Django 5.1.7 on 2025-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_forum_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('pregnancy', 'Pregnancy'), ('postpartum', 'Postpartum'), ('parenting', 'Parenting'), ('mental_health', 'Mental Health')], default='general', max_length=20),
        ),
    ]
