# Generated by Django 5.1.7 on 2025-03-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_photos/'),
        ),
    ]
