# Generated by Django 5.1.6 on 2025-03-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_healthcare_provider_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mom', 'mom'), ('healthcare_provider', 'Healthcare Provider'), ('admin', 'Admin')], default='mom', max_length=20),
        ),
    ]
