# Generated by Django 5.1.7 on 2025-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mom', 'Mom'), ('healthcare_provider', 'Healthcare Provider'), ('admin', 'Admin')], default='mom', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
